<?php
// $Id: og_seo_parameter.module,v 1.45 2009/12/22 14:56:21 sun Exp $

define('KAVERET_DEFAULT_SEO_PARAMETER_PREFIX','site=');
define('KAVERET_HESCHEL_SEO_PARAMETER','heschel.org.il');
define('KAVERET_HESCHEL_NODE',965);

// Define custom_url_rewrite_outbound() function if not already defined.
if (!function_exists('custom_url_rewrite_outbound')) {
  function custom_url_rewrite_outbound(&$path, &$options, $original_path) {
    og_seo_parameter_url_outbound_alter($path, $options, $original_path);
  }
}


/**
 * @file
 * Assign additional user roles to members of organic groups within the group context.
 *
 * For detailed documentation:
 * @see og_seo_parameter_init()
 */

/**
 * Implementation of hook_help().
 *
function og_seo_parameter_help($path, $arg) {
  switch ($path) {
    case 'admin/og/og_user_roles':
      $output = '<p>' . t('Group members with the %permission <a href="@permissions-url">permission</a> can assign additional roles to individual users of a group that only apply within the context of a group.', array('%permission' => 'configure member roles', '@permissions-url' => url('admin/user/permissions'))) . '</p>';
      return $output;

    case 'og/users/%/roles':
      $output = '<p>' . t('This form allows to grant additional user roles to individual members of this group. Any additional permissions only apply to the context of this group and not globally.') . '</p>';
      return $output;
  }
}*/

/**
 * Implementation of hook_perm().
 */
function og_seo_parameter_perm() {
  return array(
    'configure group seo parameter for all groups',
    'configure group seo parameter for my group',
  );
}

/**
 * Implementation of hook_menu().
 *
function og_seo_parameter_menu() {
  $items['admin/og_seo_parameter'] = array(
    'title' => 'Group SEO parameter',
    'description' => 'Configure group SEO parameter.',
    'page callback' => 'drupal_get_form',
    //??'page arguments' => array('og_user_roles_admin_settings'),
    'access arguments' => array('configure group seo parameter for all groups'),
    'file' => 'og_user_roles.pages.inc',
  );
  return $items;
}*/


/**
 * Implementation of hook_theme().
 *
function og_seo_parameter_theme() {
  return array(
    'og_user_roles_page_form' => array(
      'arguments' => array('form' => array()),
      'file' => 'og_user_roles.pages.inc',
    ),
  );
}*/

/**
 * @defgroup og_seo_parameter_privilege_escalation OG user roles privilege escalation
 * @{
 */

/**
 * Implementation of hook_init().
 *
 * In og_init(), Organic Groups invokes menu_get_item() via
 * og_determine_context(). menu_get_item() performs an access check for the
 * current path, which is irreversible (statically cached). Since we want to
 * alter the user's roles before the rest of the system (especially the menu
 * system) performs access checks, we need to invoke a fork of
 * og_determine_context(), which uses custom implementations of menu_get_item()
 * and menu_get_object() to retrieve the current group context, so we can
 * properly assign additional roles for the user. After this manipulation, the
 * rest of the system behaves as usual - i.e. og_init() consults the menu system
 * to determine the context, and if the additional user roles allow access to
 * the current path, the menu system will allow access and cache that
 * statically.
 *
 * This manipulation is only possible, since we decreased the module weight of
 * og_seo_parameter, so og_seo_parameter_init() runs before og_init() and probably
 * before most other implementations of hook_init().
 * hook_boot() cannot be used, because the path system is not yet initialized
 * there.
 *
 * @see og_determine_context()
 * @see og_seo_parameter_determine_context()
 * @see og_seo_parameter_menu_get_item()
 * @see og_seo_parameter_menu_get_object()
 *
function og_seo_parameter_init() {
  global $user;

  // Try to determine group context using customized menu system functions.
  $group_node = og_seo_parameter_determine_context();

  // If no group context could be determined, additionally check for a custom
  // group context that might have been set via og_set_group_context() to allow
  // for usage of extended context support in organic groups. Only modules that
  // set a context before og_seo_parameter_init() runs will have an effect. Since
  // og_seo_parameter module sets its weight to -1, other modules may have to align
  // their module weights to be able to set a custom group context early enough.
  if (!isset($group_node)) {
    $group_node = og_get_group_context();
  }

  // Assign additional user roles to current user (if any).
  og_seo_parameter_grant_roles($user, $group_node);
}*/

/**
 * Set group context using the menu system.
 *
 * The only difference to the original og_determine_context() is that we are
 * intentionally using our own menu system functions, so we can determine
 * the group context without setting access for the current menu path (which
 * is statically cached in menu_get_item()).
 *
 * @return
 *   A group node object, or NULL if not a group page.
 *
 * @see og_determine_context()
 *
function og_seo_parameter_determine_context() {
  $item = og_seo_parameter_menu_get_item();
  $object = og_seo_parameter_menu_get_object();

  // Use the menu system to get the path.
  $path = $item['path'];

  // Check if this is an existing node.
  if (!empty($object->nid)) {
    $node = $object;
  }
  // Check if we are in the node add page.
  elseif (strpos($path, 'node/add') === 0 && !empty($_REQUEST['gids'])) {
    // URL pattern: node/add/story?gids[]=1
    $gid = intval(current($_REQUEST['gids']));
    $node = node_load($gid);
  }
  elseif ((!empty($item['map'][0]) && $item['map'][0] == 'og' && !empty($item['map'][2])) || $path == 'comment/reply/%') {
    if (is_numeric($item['map'][2])) {
      $node = node_load($item['map'][2]);
    }
    else {
      $node = og_seo_parameter_menu_get_object('node', 2);
    }
  }
  elseif ($path == 'comment/edit' || $path == 'comment/delete') {
    // Get the node from the comment object.
    $comment = _comment_load($item['page_arguments'][0]);
    $node = node_load($comment->nid);
  }

  if (!empty($node) && ($group_node = og_determine_context_get_group($node))) {
    return $group_node;
  }
}*/

/**
 * Get a router item.
 *
 * Due to the static $router_items, our initial query in hook_init() would
 * perform a real access check for the current path and we would be no longer
 * be able to grant privileges.
 *
 * In Drupal 7, this fork can probably be replaced with
 * @code
 *   drupal_static_reset('menu_get_item');
 * @endcode
 *
 * @see menu_get_item()
 *
function og_seo_parameter_menu_get_item($path = NULL, $router_item = NULL) {
  static $router_items;
  if (!isset($path)) {
    $path = $_GET['q'];
  }
  if (isset($router_item)) {
    $router_items[$path] = $router_item;
  }
  if (!isset($router_items[$path])) {
    $original_map = arg(NULL, $path);
    $parts = array_slice($original_map, 0, MENU_MAX_PARTS);
    list($ancestors, $placeholders) = menu_get_ancestors($parts);

    if ($router_item = db_fetch_array(db_query_range('SELECT * FROM {menu_router} WHERE path IN ('. implode (',', $placeholders) .') ORDER BY fit DESC', $ancestors, 0, 1))) {
      // OGUR: Allow privilege escalation; do not invoke access callbacks.
      $map = og_seo_parameter_menu_translate($router_item, $original_map);
      if ($map === FALSE) {
        $router_items[$path] = FALSE;
        return FALSE;
      }
      // OGUR: Allow privilege escalation; always load map.
      //if ($router_item['access']) {
        $router_item['map'] = $map;
        $router_item['page_arguments'] = array_merge(menu_unserialize($router_item['page_arguments'], $map), array_slice($map, $router_item['number_parts']));
      //}
    }
    $router_items[$path] = $router_item;
  }
  return $router_items[$path];
}*/

/**
 * Handles dynamic path translation and menu access control.
 *
 * Certain menu access callbacks (like _node_revision_access()) statically cache
 * the result of the access check for performance. We only want to retrieve and
 * determine the group context in og_seo_parameter_init(), resp.
 * og_seo_parameter_menu_get_item(), where no additional roles have been granted
 * yet. _menu_translate() would normally also invoke the access callback for the
 * current page. Therefore, certain menu access callbacks, which statically
 * cache their result, would return that result in subsequent invocations (i.e.
 * FALSE when the user does not have permissions).
 *
 * Since OG user roles only wants to retrieve context and all of the regular
 * menu system's behavior is and should not be modified, we simply skip the
 * access check in this fork.
 *
 * In Drupal 7, this wrapper can probably be replaced with (or similar):
 * @code
 *   drupal_static_reset('_node_revision_access');
 * @endcode
 *
 * @see _menu_translate()
 * @see og_seo_parameter_menu_get_item()
 *
function og_seo_parameter_menu_translate(&$router_item, $map, $to_arg = FALSE) {
  if ($to_arg) {
    // Fill in missing path elements, such as the current uid.
    _menu_link_map_translate($map, $router_item['to_arg_functions']);
  }
  // The $path_map saves the pieces of the path as strings, while elements in
  // $map may be replaced with loaded objects.
  $path_map = $map;
  if (!_menu_load_objects($router_item, $map)) {
    // An error occurred loading an object.
    $router_item['access'] = FALSE;
    return FALSE;
  }

  // Generate the link path for the page request or local tasks.
  $link_map = explode('/', $router_item['path']);
  for ($i = 0; $i < $router_item['number_parts']; $i++) {
    if ($link_map[$i] == '%') {
      $link_map[$i] = $path_map[$i];
    }
  }
  $router_item['href'] = implode('/', $link_map);
  $router_item['options'] = array();
  // OGUR: Allow privilege escalation; do not invoke access callbacks.
  //_menu_check_access($router_item, $map);
  
  // For performance, don't localize an item the user can't access.
  if (!empty($router_item['access'])) {
    _menu_item_localize($router_item, $map);
  }

  return $map;
}*/

/**
 * Get a loaded object from a router item.
 *
 * @see menu_get_object()
 * @see og_seo_parameter_menu_get_item()
 *
function og_seo_parameter_menu_get_object($type = 'node', $position = 1, $path = NULL) {
  $router_item = og_seo_parameter_menu_get_item($path);
  if (isset($router_item['load_functions'][$position]) && !empty($router_item['map'][$position]) && $router_item['load_functions'][$position] == $type .'_load') {
    return $router_item['map'][$position];
  }
}*/


/**
 * @} End of "defgroup og_seo_parameter_privilege_escalation".
 */

/**
 * Implementation of hook_og().
 *
 * @param $op
 *   The operation performed; 'user insert', 'user update', 'user delete'.
 * @param $nid
 *   Node ID of the group.
 * @param $uid
 *   The user ID.
 * @param $args
 *   Associative array containing details about the subscription.
 *
function og_seo_parameter_og($op, $nid, $uid, $args = array()) {
  switch ($op) {
    case 'user insert':
      // Add default role for new group members, if configured.
      if ($default_role = og_seo_parameter_get_group_default_role($nid)) {
        og_seo_parameter_role_add($nid, $uid, $default_role);
      }

      // Add default role for new group admins, if configured.
      if (isset($args['is_admin']) && $args['is_admin']) {
        if (($default_admin_role = variable_get('og_user_roles_default_admin_role', 0)) && $default_admin_role != $default_role) {
          og_seo_parameter_role_add($nid, $uid, $default_admin_role);
        }
      }
      break;

    case 'user update':
      $default_admin_role = variable_get('og_user_roles_default_admin_role', 0);
      $default_role = og_seo_parameter_get_group_default_role($nid);
      if ($default_admin_role > 0 && $default_admin_role != $default_role) {
        // Grant role for new group admin.
        if (isset($args['is_admin']) && $args['is_admin']) {
          og_seo_parameter_role_add($nid, $uid, $default_admin_role);
        }
        // Delete role for obsolete group admin.
        else {
          og_seo_parameter_role_delete($nid, $uid, $default_admin_role);
        }
      }
      break;

    case 'user delete':
      // Remove all group roles for unsubscribed user.
      og_seo_parameter_role_delete($nid, $uid);
      break;
  }
}*/

/**
 * Implementation of hook_nodeapi().
 *
function og_seo_parameter_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {
    case 'load':
      if (og_is_group_type($node->type)) {
        $rid = db_result(db_query("SELECT default_role FROM {og_users_roles_group} WHERE gid = %d", $node->nid));
        if ($rid) {
          $node->og_user_roles_default_role = $rid;
        }
      }
      break;

    case 'insert':
      if (!empty($node->og_user_roles_default_role) && og_is_group_type($node->type)) {
        db_query("INSERT INTO {og_users_roles_group} (gid, default_role) VALUES (%d, %d)", $node->nid, $node->og_user_roles_default_role);
      }
      break;

    case 'update':
      if (!empty($node->og_user_roles_default_role) && og_is_group_type($node->type)) {
        db_query("UPDATE {og_users_roles_group} SET default_role = %d WHERE gid = %d", $node->og_user_roles_default_role, $node->nid);
        if (!db_affected_rows()) {
          db_query("INSERT INTO {og_users_roles_group} (gid, default_role) VALUES (%d, %d)", $node->nid, $node->og_user_roles_default_role);
        }
      }
      break;

    case 'delete':
      // Remove all data for a deleted group.
      if (og_is_group_type($node->type)) {
        db_query("DELETE FROM {og_users_roles} WHERE gid = %d", $node->nid);
        db_query("DELETE FROM {og_users_roles_group} WHERE gid = %d", $node->nid);
      }
      break;
  }
}*/

/**
 * Implementation of hook_link().
 *
 * @todo Move into OG.
 *
function og_seo_parameter_link($type, $object, $teaser = FALSE) {
  if (isset($links['book_add_child'])) {
    $group_node = og_get_group_context();
    if (is_object($group_node) && !empty($group_node->nid)) {
      $links['book_add_child']['query'] .= '&gids[]=' . $group_node->nid;
    }
  }
}*/


/**
 * Implementation of hook_link_alter().
 *
 * @todo Move into OG.
 *
function og_seo_parameter_link_alter(&$links, $node) {
  if (isset($links['book_add_child'])) {
    $group_node = og_get_group_context();
    if (is_object($group_node) && !empty($group_node->nid)) {
      $links['book_add_child']['query'] .= '&gids[]=' . $group_node->nid;
    }
  }
}*/

/**
 * Return assigned roles for a user in a group.
 *
function og_seo_parameter_get_roles_by_group($gid, $uid) {
  $assigned_roles = array();
  $result = db_query("SELECT rid FROM {og_users_roles} WHERE uid = %d AND gid = %d", $uid, $gid);
  while ($rid = db_result($result)) {
    $assigned_roles[$rid] = $rid;
  }
  return $assigned_roles;
}*/

/**
 * Grant a role for a user in a group.
 *
 * @param $gid
 *   The group ID.
 * @param $uid
 *   The user ID.
 * @param $rid
 *   The role ID to grant.
 *
function og_seo_parameter_role_add($gid, $uid, $rid) {
  $granted = db_result(db_query_range("SELECT rid FROM {og_users_roles} WHERE gid = %d AND uid = %d AND rid = %d", $gid, $uid, $rid, 0, 1));
  if (!$granted) {
    db_query("INSERT INTO {og_users_roles} (uid, gid, rid) VALUES (%d, %d, %d)", $uid, $gid, $rid);
  }
}*/

/**
 * Revoke a role or all roles for a user in a group.
 *
 * @param $gid
 *   The group ID.
 * @param $uid
 *   The user ID.
 * @param $rid
 *   (Optional) The role ID to remove. If omitted, all roles are removed.
 *
function og_seo_parameter_role_delete($gid, $uid, $rid = NULL) {
  if (is_null($rid)) {
    db_query("DELETE FROM {og_users_roles} WHERE gid = %d AND uid = %d", $gid, $uid);
  }
  else {
    db_query("DELETE FROM {og_users_roles} WHERE gid = %d AND uid = %d AND rid = %d", $gid, $uid, $rid);
  }
}*/

/**
 * Retrieve all roles assignable in a group.
 *
function og_seo_parameter_get_group_roles($node_type) {
  $roles = array();
  $allowed_roles = array_filter(variable_get("og_user_roles_roles_{$node_type}", array()));
  $user_roles = user_roles();
  foreach ($allowed_roles as $rid => $checked) {
    $roles[$rid] = check_plain($user_roles[$rid]);
  }
  return $roles;
}*/

/********************************************************
 * Implementation of hook_form_alter().
 *
function og_seo_parameter_form_alter(&$form, &$form_state, $form_id) {
  // Add default user role option to node form.
  // @todo Consider a better UI location for this.
  if (isset($form['#node']) && $form_id == $form['#node']->type . '_node_form') {
    $node = $form['#node'];
    if (og_is_group_type($node->type) && og_seo_parameter_configure_access($node)) {
      $default = (!empty($node->og_user_roles_default_role) ? $node->og_user_roles_default_role : 0);
      $options = array(0 => t('<default>'));
      $options += og_seo_parameter_get_group_roles($node->type);

      $form['og_user_roles_default_role'] = array(
        '#type' => 'select',
        '#title' => t('Default role for new members'),
        '#options' => $options,
        '#default_value' => $default,
        '#description' => t('Configure a default role to be assigned to new group members.'),
      );
    }
  }
}*/

/**
 * Implementation of hook_content_extra_fields().
 *
function og_seo_parameter_content_extra_fields($type_name) {
  if (og_is_group_type($type_name)) {
    $extra['og_user_roles_default_role'] = array(
      'label' => t('Default role for new members'),
      'description' => t('Configure a default role to be assigned to new group members.'),
      'weight' => 0,
    );
    return $extra;
  }
}*/

/**
 * check if user is allowed to modify this group's SEO URL parameter
 */
function og_seo_parameter_configure_access($node){
  // is this an administrator?
  if ( user_access('configure group seo parameter for all groups')) {
  	
  	return true;
  } //and node's authour is current user	
  // is this the group admin?
  dprint_r($node0);
  return user_access('configure group seo parameter for my group'); //and node's authour is current user	
}

/**
 * Outbound URL rewrite helper
 * Rewrite URLs: attach/remove subdmain as appropriate
 */
function og_seo_parameter_url_outbound_alter(&$path, &$options, $original_path, $clear_path_cache = FALSE) {
  // Cache outbound paths
  static $paths = array();
  // Clear path cache (sometimes needed when new subdomains created - e.g. og)
  if ($clear_path_cache) {
    $paths = array();
  }
 
  // Process path if not in cache
  if (!isset($paths[$original_path])) {
    if ((arg(0) == 'node') && (is_numeric(arg(1)))) {
  	  $nid = arg(1);
    } 
    
    // on non-node paths, no seo parameter is needed.
    
    // BEWARE OF GROUPS THAT ARE HIDDEN FOR NOT-LOGGED IN USERS 
    // - LOGIC ASSUMES PUBLICLY VISIBLE GROUP
    $should_add_seo_parameter = isset($nid) 
                                   && is_group_context($nid, KAVERET_HESCHEL_NODE);
  
    if ($should_add_seo_parameter) {
  	  $options['query'] = (($options['query']) ? "&" : "")
  	    . KAVERET_DEFAULT_SEO_PARAMETER_PREFIX . KAVERET_HESCHEL_SEO_PARAMETER;  
  	    //drupal_set_message('adding seo param for link: '.$path. ' so query is now: '.$options['query']);
    }
  	
    // Cache $path in case it was altered
    $paths[$original_path]['query'] = ($should_add_seo_parameter)
      ? $options['query']
      : "";
  } 
  else if ($paths[$original_path]['query'] == "") {
  	return;
  } else $options['query'] = (($options['query']) ? "&" : "") . $paths[$original_path]['query'];  
}

/*
 * check if $nid is same as $gid
 * if not - check if $nid is a group-post-type that is posted in $gid
 * 
 */
function is_group_context($nid, $gid) {
  if ($nid == $gid) {
    return true;
  }
  
  $node = node_load($nid);

  if (empty($node)) {
    return false;
  }  
  
  $group = og_determine_context_get_group($node);
  
  if (isset($group)) {
    if ($group->nid == $gid) {
    	return true;
    }
    /*$node_form = ((arg(0) == 'node') && ((is_numeric(arg(1)) && (arg(2) == 'edit')) 
                   || (arg(1) == 'add')));
    */
  }
	
}